### PR TITLE
Wait for SLAK and INAK bits when changing mode

### LINKED ISSUE #7: can initialization process doesn't work on stm32f4
This does seem to work (though I haven't yet sent a message):

```rust
    dp.RCC.apb2enr.write(|w| w.syscfgen().enabled());

    let gpioa = dp.GPIOA.split();
    let gpiob = dp.GPIOB.split();
    let gpioc = dp.GPIOC.split();
    let mut rcc = dp.RCC.constrain();

    let clocks = rcc
        .cfgr
        .use_hse(16.mhz())
        .sysclk(48.mhz())
        .pclk1(24.mhz())
        .freeze();

    let mut delay = Delay::new(cp.SYST, clocks);

    CAN1::enable(&mut rcc.apb1);

    dp.CAN1.mcr.modify(|_, w| w.sleep().clear_bit());
    let mut waiting = true;
    while waiting {
        let msr = dp.CAN1.msr.read();
        if msr.slak().bit_is_set() {
            waiting = false;
        }
    }

    dp.CAN1.mcr.modify(|_, w| w.dbf().clear_bit());

    let r_mcr = dp.CAN1.mcr.read().bits();
    let r_msr = dp.CAN1.msr.read().bits();
    let r_tsr = dp.CAN1.tsr.read().bits();

    /* request initializiation */
    dp.CAN1.mcr.modify(|_, w| w.inrq().set_bit());
    let mut waiting = true;
    while waiting {
        let msr = dp.CAN1.msr.read();
        if msr.inak().bit_is_set() {
            waiting = false;
        }
    }

    dp.CAN1.btr.modify(|_, w| unsafe { w.bits(0x001c_0003) });

```

compare to the initialization process in this pacakge

```rust
        can.mcr
            .modify(|_, w| w.sleep().clear_bit().inrq().set_bit());
        while can.msr.read().inak().bit_is_clear() {}

        can.mcr
            .modify(|_, w| w.sleep().set_bit().inrq().clear_bit());
        while can.msr.read().slak().bit_is_clear() {}

        let msr = can.msr.read();
        while !msr.slak().bit_is_set() {
            can.mcr
                .modify(|_, w| w.abom().set_bit().sleep().clear_bit());
        }
```

I'm not sure why it's currently done this way, but the `slak()` bit is not set.

### PR DESCRIPTION
**Pull request by timokroeger**
fixes #7

@xoviat can you please test if this fixes the problems you observed on stm32f4xx?

### CODE REVIEW

**Comment by mdrobnak** [comment]
I have tested this out today, using https://github.com/mdrobnak/stm32f4xx-hal/blob/bxcan/examples/can-send.rs and it was producing 2000 frames a second. Looks good.

**Comment by xoviat** [comment]
@mdrobnak I'm going to test this tomorrow, but how did you find the the correct pin setting was alternate_af9?

**Comment by mdrobnak** [comment]
> @mdrobnak I'm going to test this tomorrow, but how did you find the the correct pin setting was alternate_af9?

In the microcontroller docs there's a pin mapping to Alternate Function guide. https://www.st.com/resource/en/datasheet/dm00037051.pdf Table 9.

-Matt

**Comment by xoviat** [comment]
@timokroeger There may be some clock issues somewhere in the stack (at least it seems to me at this point), but this seems to work for me as a good first step. I'm happy with the API, and I can submit further non-breaking changes to fix the clock issues if I find them. Please go ahead and merge this.

**Comment by jonas-schievink** [comment]
bxcan does no clock configuration besides writing the raw user-provided value to the bit timing register

**Comment by mdrobnak** [comment]
This already works better than the previous driver I was using so anything moving forward is good. Thanks!

**Comment by xoviat** [comment]
@jonas-schievink I mean 'somewhere in the stack'. I haven't looked into the issue yet, so there's nothing for me to submit at this point.

**Pull request merged**
